chore: upgrade mongodb to 6.0.0
jdesboeufs/connect-mongo pull request #473
Opened 2023-08-28 21:44 UTC by saltire

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Updates the `mongodb` dependency from v5.0.0 to v6.0.0.

I didn't see anything in the [release notes](https://github.com/mongodb/node-mongodb-native/blob/HEAD/etc/notes/CHANGES_6.0.0.md) to warrant changes to the code, so this PR just updates the MongoDB and Node versions, following the PR for v5.

- **Checklist:**

- [n/a] Added test cases
- [x] Updated changelog

2023-09-01 18:11 UTC, saltire commented
@jdesboeufs @mingchuno

2023-09-02 17:44 UTC, saltire commented
Added fix for failed build.

2023-09-20 21:50 UTC, saltire commented
Looks like the build needs to be manually approved, any maintainer out there willing to run it? @jdesboeufs @mingchuno

2023-09-21 05:33 UTC, thuh-reflact commented
> Looks like the build needs to be manually approved, any maintainer out there willing to run it? @jdesboeufs @mingchuno

That would be great.... GOGOGO

2023-09-26 15:41 UTC, apydo commented
@MarkoCen, could you please approve it and merge ?

2023-09-26 20:20 UTC, jdesboeufs commented
I will look at this.

2023-10-13 17:22 UTC, krzysztof-cislo commented
Any chance to merge this PR soon and create new release?

2023-10-14 08:07 UTC, jdesboeufs commented
Since `mongodb@6.0` introduces a big breaking change (`findOneAndX` not returning metadata by default), I'm not sure we should "force" having `mongodb >= 6.0`.

This module doesn't use specific `mongodb@6.0` features. What do you think?

2023-10-14 10:27 UTC, jdesboeufs requested changes
Thank you for your contribution!
I suggest some changes so we will be able to release a minor version quickly, and then we will release a major dropping old Node.js versions.

2023-10-14 10:27 UTC, jdesboeufs commented on .github/workflows/sanity.yml
> -        node-version: [14.x, 16.x, 18.x]
We have to keep this for now

2023-10-14 10:27 UTC, jdesboeufs commented on CHANGELOG.md
> +## [6.0.0] - 2023-08-28
It's not your responsability to release :)
The next release will be `5.1.0`!

2023-10-14 10:27 UTC, jdesboeufs commented on CHANGELOG.md
> +- Upgraded peer dependency `mongodb` to 6.0.0
Not needed. See other comment.

2023-10-14 10:27 UTC, jdesboeufs commented on README.md
> +* Support [native MongoDB driver](http://mongodb.github.io/node-mongodb-native/) `>= 6.0`
Not needed

2023-10-14 10:27 UTC, jdesboeufs commented on package.json
> +  "version": "6.0.0",
Please let this unchanged

2023-10-14 10:27 UTC, jdesboeufs commented on package.json
> +    "node": ">=16.20.0"
Not needed for now. We will drop versions prior 16 LTS in the next major release.

2023-10-14 10:27 UTC, jdesboeufs commented on package.json
> +    "mongodb": "^6.0.0"
```suggestion
    "mongodb": ">= 5.0.0 < 7"
```

2023-10-14 16:34 UTC, saltire commented
@jdesboeufs Thanks for reviewing! Implemented changes, please take a look.

2023-10-14 16:37 UTC, jdesboeufs approved these changes

2023-10-14 16:41 UTC, saltire commented
Hmm do we have to drop Node 14 if we want to support mongodb v6?

2023-10-14 16:49 UTC, jdesboeufs commented
No but sanity workflo must be updated according to relaxed peer dependency.
I'm working on this!

2023-10-14 17:14 UTC, jdesboeufs requested changes
And to test against `mongodb@6` I suggest you to add a new step in `sanity.yml`.
Something like this:
```yaml
- run: yarn add mongodb@^6 && yarn test
  if: ${{ matrix.node-version !== '4.x' }}
```

2023-10-14 17:14 UTC, jdesboeufs commented on package.json
> +    "mongodb": ">= 5.0.0 < 7"
I made a mistake here
```suggestion
    "mongodb": ">= 5.1.0 < 7"
```

2023-10-14 17:14 UTC, jdesboeufs commented on package.json
> +    "mongodb": "^6.0.0",
Finally please let this part unchanged at the moment.

2023-10-14 17:15 UTC, jdesboeufs commented
If you prefer I can finish. No problem with this :)

2023-10-14 17:58 UTC, saltire commented
OK, updated. Not sure if the extra CI step is in the right place, let me know if it needs fixing.

2023-10-14 18:18 UTC, jdesboeufs requested changes

2023-10-14 18:18 UTC, jdesboeufs commented on .github/workflows/sanity.yml
> +        if: ${{ matrix.node-version }} !== '14.x'
```suggestion
        if: ${{ matrix.node-version !== '14.x' }} 
```

2023-10-14 18:26 UTC, jdesboeufs approved these changes

2023-10-14 18:28 UTC, merged